UPDATE `world`.`creature_template` SET `unit_class` = '1' WHERE `entry` = '68045';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180130';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180101';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '186922';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181473';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181209';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182011';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180302';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180302';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180425';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180002';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181465';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182012';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180004';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180208';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181190';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187095';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180025';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180001';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180015';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181256';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181254';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180000';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180411';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182008';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181179';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181214';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181024';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181470';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180429';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182215';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181274';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181474';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181325';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181466';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181225';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181241';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181189';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181137';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181149';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180808';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181276';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181340';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182028';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182044';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181151';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182148';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181191';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181207';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180306';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182405';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180313';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180442';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180426';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180426';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187034';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182065';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180426';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181630';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182141';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182041';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '186709';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181311';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181327';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182440';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180412';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181040';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181044';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181028';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181136';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181216';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181220';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181305';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182618';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181273';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182010';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181022';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181006';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181178';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181182';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181210';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187841';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181198';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187042';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181312';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180303';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181472';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181219';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187287';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181203';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180405';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180421';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180430';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180017';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180011';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181164';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180304';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185524';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187339';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185518';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181334';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181218';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180220';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180423';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180427';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181163';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182394';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180310';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180301';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182361';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182331';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182490';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181140';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181181';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181217';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181245';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181468';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188138';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181437';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180022';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181014';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181038';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181437';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180404';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180420';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182444';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180409';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182014';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181322';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187389';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182038';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187840';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181172';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181188';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181184';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181002';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180416';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180432';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188757';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185525';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182040';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182400';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181016';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185433';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181148';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181212';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180407';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188134';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181221';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180005';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180009';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182139';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181215';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181471';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182495';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185711';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180012';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180008';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180016';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180024';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181150';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180021';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188006';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181187';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180439';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180434';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182001';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '184817';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181001';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181008';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182045';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180419';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181467';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181242';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181004';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180431';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187805';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181147';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181211';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180438';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181253';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181206';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181032';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181272';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181252';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182033';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181519';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '186706';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180006';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180018';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182406';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185483';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180003';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180007';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180010';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180014';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180019';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180023';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180102';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180103';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180107';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180109';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180799';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180854';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180305';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180307';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180308';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180309';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180311';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180312';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180401';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180402';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180403';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180406';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180408';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180415';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180417';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180424';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180428';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180433';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180435';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180437';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180440';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180441';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180443';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180445';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180446';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181010';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181012';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181020';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181026';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181030';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181034';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181036';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181138';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181146';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181170';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181171';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181173';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181174';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181180';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181183';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181185';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181186';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181192';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181201';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181204';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181205';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181208';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181213';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181226';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181249';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181251';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181255';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181302';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181303';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181304';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181307';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181319';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181320';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181321';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181323';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181324';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181326';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181435';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181439';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181464';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181469';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181554';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181631';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182015';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182016';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182017';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182036';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182047';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182066';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182085';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182130';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182210';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182267';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182357';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182493';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '183377';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185430';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185519';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185520';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185521';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185523';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '185537';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '156197';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '186083';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187842';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188507';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '188661';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '180444';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '187785';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '181202';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '182067';
UPDATE `world`.`creature_template` SET `faction_A` = '35' , `faction_H` = '35' WHERE `entry` = '186197';

UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66361';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61793';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63067';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64593';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65066';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66364';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66443';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66482';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65559';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64505';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66489';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66493';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66453';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66416';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66497';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66135';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65744';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66487';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66455';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66414';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66486';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '57670';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66490';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65742';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '56134';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66494';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63014';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65008';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65051';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '59652';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63596';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '57638';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64876';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63479';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '62159';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '62098';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66488';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '67185';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61126';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66439';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '57669';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '32930';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66496';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66445';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66485';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66126';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65651';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66495';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66481';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '37921';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65558';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66454';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '67186';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66966';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66444';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '56434';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '56784';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '57692';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '60741';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61127';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61463';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61528';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66492';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61757';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61792';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '61796';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66438';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63061';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63070';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63073';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63075';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63077';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63080';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63083';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63086';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63310';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63478';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '63626';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64330';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64506';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64543';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '64875';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65048';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '65648';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66136';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66363';
UPDATE `world`.`creature_template` SET `exp` = '0' WHERE `entry` = '66417';




















